---
title: "Odisseia de Homero"
description: "«Não é justo levarmos a mal que ele cante a desgraça dos Dânaos. Pois as pessoas apreciam de preferência aquela canção que, recentíssima, estiver no ar para os ouvintes. Que o teu espírito e o teu coração ousem ouvir.»"
date: 2026-07-12
categories: [literature, review, classic, greek]
comments: false
---

> Avançando com leveza, a nau cortou as ondas do mar,\
> Transportando um homem cujos conselhos igualam\
> Os dos deuses, que já sofrera muitas tristezas no coração,\
> Que atravessara as guerras dos homens e as ondas dolorosas,\
> Mas que agora dormia em paz, esquecido de tudo quanto sofrera.*

**Se Odisseu é descrito, no primeiro verso do poema, como um homem versátil, de "muitas voltas"** (_polútropos_, embora o sentido da palavra seja incerto), a Odisseia de Homero é, conforme nos chegou ao presente, sem dúvida, um livro de muitos sentidos. E para percebermos esses sentidos, temos de perceber um pouco mais sobre a génese desta obra.

A Odisseia é, para todos os efeitos, o mais provável, **uma adaptação**, na melhor das hipóteses, uma transcrição daquilo que se presume ser uma experiência oral. Ao contrário do que estamos acostumados a pensar, a Odisseia não é, de forma alguma, a "verdadeira história de Odisseu", conforme o poeta a concebeu originalmente, mas, sim, uma versão - mais - uma manta de retalhos de versões diferentes, reunidas num exercício de edição fragmentário e que se prolongou ao longo de muito tempo.

> No entanto deixai-me jantar, apesar da minha tristeza.\
> Pois nada existe de mais detestável do que o estômago,\
> Que à força obriga o homem a pensar em comida,\
> Mesmo quando oprimido com tristeza no espírito,\
> Como agora me sinto oprimido; mas de modo incessante\
> Me recorda o estômago a comida e a bebida, fazendo-me\
> Esquecer tudo o que sofri, exigindo que o encha.*

A beleza do poema de mais de 12 mil versos deixa-nos assumir, talvez ingenuamente, que uma grande parte destes versos terão sido da autoria do poeta Homero (que, já agora, segundo os estudiosos, mais certamente será um homem completamente diferente do poeta da Ilíada). Mas essa integridade não nos resguarda da fragmentação que prolifera no texto.

**Isto era algo do qual eu não fazia a mínima ideia** quando me propus a ler a (devo dizer, magnífica) tradução do Prof. Frederico Lourenço da Odisseia, da Quetzal. Como devem imaginar, fiquei bastante surpreendido e, até, desapontado, ao deparar-me, no decurso da minha leitura, com sequências completamente desconexas e incongruentes, seja pelo número sempre crescente dos pretendentes de Penélope (que, ao longo dos séculos, aparenta ter crescido de 12 Itacenses para 108 homens oriundos da maior variedade de geografias), pelas personagens que apareciam e desapareciam de cena espontaneamente, pelos jantares seguidos de jantares seguidos de jantares e pelas mudanças abruptas de vontades e opiniões das personagens (por vezes, no espaço de poucos versos!), para não falar da justaposição trapalhona de episódios, mitos e demais (a destacar, do Canto XI, o foleiríssimo _cameo_ de Aquiles no submundo, digno do rótulo de _fan service_).

> Tal como é bem-vindo um sinal de vida no pai que os filhos\
> Viram acamado e sofrendo grandes dores durante muito tempo,\
> Definhando, e já quase o tocara a divindade detestável,\
> Mas depois os deuses o libertam da sua doença -\
> Assim a Odisseu a terra e as árvores pareciam uma amável visão.*

Gradualmente, a minha perspetiva mudou. Apercebi-me de que não estava a ler uma história, mas, sim, uma coletânea de mitos, contos e dizeres sobre esta figura mitológica - Odisseu - esse homem de "muitas voltas", capaz tanto de grandes astúcias, como cruel violência, tanto entregue às suas raízes itacenses, como repetidamente adúltero.

Foi sob o foco desta nova perspetiva que a verdadeira história de Odisseu pôde brilhar através das pesadas roupas com que os séculos de trabalho editorial a cobrem. Desde excertos lindíssimos, demonstrativos de um mestre poeta por detrás da trama, a episódios fundamentalmente familiares, _tropes_ que, nos dias de hoje, permeiam a cultura Ocidental.

> Mas este homem infeliz até aqui vagueou: dele devemos tratar,\
> Pois é de Zeus que vêm todos os estrangeiros e mendigos;\
> E qualquer dádiva, embora pequena, é bem-vinda.*

**Ao terminar a minha leitura da obra**, não pude deixar de sentir um misto de admiração e frustração, este último sentimento exacerbado pelo final altamente desapontante, que rivalizou e ressuscitou da minha memória outros míticos _stinkers_, finais distintivamente azedos, como os finais dos filmes musicais Easter Parade (1948) e Annie Get Your Gun (1950), excelentes comparações com o final da Odisseia, pelo peso da tradição e o chauvinismo latente a puxarem a narrativa para uma conclusão desinteressante, mais ainda, flácida, e, pior de tudo, incoerente.

É, sem dúvida, frustrante ter concluído de forma tão agridoce o livro, porque tive vislumbres vários de uma odisseia verdadeiramente notável, inúmeros momentos marcados por ousadia, tragédia e paixão. **Assim aguardo, ansioso, mas acautelado, pela próxima adaptação da história, na esperança de que me satisfaça esta fome por aquela que porventura será, aos meus olhos, a verdadeira história de Odisseu.**

> Assim falou; e uma nuvem negra de dor se apoderou de Laertes.\
> Com ambas as mãos agarrou em terra misturada com cinza\
> E atirou-a por cima da cabeça, gemendo incessantemente.\
> Comoveu-se o coração de Odisseu e nas narinas sentiu\
> Uma dor lancinante, ao ver naquele estado o pai amado.\
> Lançou-se a ele, com beijos e abraços, e disse estas palavras:\
> «Eu próprio sou aquele por quem perguntaste, ó pai.»*

\* **Odisseia, Homero (trad. de Frederico Lourenço, Quetzal)**
