const fs = require("fs");
const path = require("path");

const MARKER = "<!-- AUTO-DISCLAIMER -->";

const DISCLAIMER = `${MARKER}
Thanks for reading!

By participating in this discussion, you agree to keep the conversation respectful.
`;

async function run({ github, context, core }) {
    const owner = context.repo.owner;
    const repo = context.repo.repo;

    const workflowRunId = process.env.GITHUB_RUN_ID;
    const timestamp = new Date().toISOString();

    function getBlogUrl(pathname) {
        // Ensure no double slashes when generating URL
        const cleanPath = pathname.replace(/^\/+|\/+$/g, ""); 
        return `https://www.${owner}.com/${cleanPath}/`;
    }

    const discussionBodyTemplate = (slug) => `
This discussion was automatically generated by workflow run **${workflowRunId}** at **${timestamp}**.

[View blog post](${getBlogUrl(slug)})
`;

    // 1. Get repo info
    const repoData = await github.graphql(`
        query($owner:String!, $repo:String!) {
            repository(owner:$owner, name:$repo) {
                id
                discussionCategories(first:20) {
                    nodes {
                        id
                        name
                    }
                }
            }
        }
    `, { owner, repo });

    const repoId = repoData.repository.id;

    const category = repoData.repository.discussionCategories.nodes
        .find(c => c.name === "Announcements");

    if (!category)
        throw new Error("Discussion category not found");

    // 2. Load posts from listings.json
    let posts = [];
    try {
        const listingsPath = path.join("docs", "listings.json");
        if (fs.existsSync(listingsPath)) {
            const listingsContent = fs.readFileSync(listingsPath, "utf8");
            const listingsData = JSON.parse(listingsContent);
            
            // Grab 'items' from every object in the array and flatten them into one list.
            posts = listingsData.flatMap(entry => entry.items);
            core.info(`Found ${posts.length} posts in listings.json`);

        } else {
            core.setFailed("docs/listings.json not found. Did Quarto build successfully?");
            return;
        }
    } catch (error) {
        core.setFailed(`Error parsing listings.json: ${error.message}`);
        return;
    }

    // 3. Get last 100 discussions
    const discussionsData = await github.graphql(`
        query($repoId:ID!) {
            node(id:$repoId) {
                ... on Repository {
                    discussions(first:100) {
                        nodes {
                            id
                            title
                            comments(first:100) {
                                nodes {
                                    id
                                    body
                                }
                            }
                        }
                    }
                }
            }
        }
    `, { repoId });

    const discussions = discussionsData.node.discussions.nodes;

    for (const postItem of posts) {
        // Discussion title: "/blog/year/title/"
        // We replace "index.html" with nothing, but keep the trailing slash
        const pathname = postItem.replace(/index\.html$/, ""); 
        const discussionBody = discussionBodyTemplate(pathname);
        
        let discussion = discussions.find(d => d.title === pathname);
        
        // 4. Create discussion for each post
        if (!discussion) {
            const created = await github.graphql(`
                mutation($repoId:ID!, $categoryId:ID!, $title:String!, $body:String!) {
                    createDiscussion(input:{
                        repositoryId:$repoId
                        categoryId:$categoryId
                        title:$title
                        body:$body
                    }) {
                        discussion { id }
                    }
                }
            `, {
                repoId,
                categoryId: category.id,
                title: pathname,
                body: discussionBody
            });

            discussion = { id: created.createDiscussion.discussion.id, comments: { nodes: [] } };
            core.info(`Discussion created for ${pathname}`);
        } else {
            core.debug(`Discussion already exists for ${pathname}`);
        }

        // 5. Create disclaimer comment if missing
        let disclaimerComment =
        discussion.comments?.nodes?.find(c =>
            c.body.includes(MARKER)
        );
        if (!disclaimerComment) {
            await github.graphql(`
                mutation($discussionId:ID!, $body:String!) {
                    addDiscussionComment(input:{
                        discussionId:$discussionId
                        body:$body
                    }) { comment { id } }
                }
            `, {
                discussionId: discussion.id,
                body: DISCLAIMER
            });
            core.info("Disclaimer comment created");
        }

        // 6. Update disclaimer otherwise
        else {
            await github.graphql(`
                mutation($commentId:ID!, $body:String!) {
                    updateDiscussionComment(input:{
                        commentId:$commentId
                        body:$body
                    }) { comment { id } }
                }
            `, {
                commentId: disclaimerComment.id,
                body: DISCLAIMER
            });
            core.info("Disclaimer updated");
        }
    }
}

module.exports = run;