const fs = require("fs");
const path = require("path");

const MARKER = "<!-- AUTO-DISCLAIMER -->";

const DISCLAIMER = `${MARKER}
Thanks for reading!

By participating in this discussion, you agree to keep the conversation respectful.
`;

async function run({ github, context, core }) {
    const owner = context.repo.owner;
    const repo = context.repo.repo;

    const workflowRunId = process.env.GITHUB_RUN_ID;
    const timestamp = new Date().toISOString();

    function getBlogUrl(pathname) {
        const cleanPath = pathname.replace(/^\/+/, ""); // remove leading slashes
        return `https://www.${owner}.com/${cleanPath}/`;
    }

    const discussionBodyTemplate = (slug) => `
This discussion was automatically generated by workflow run **${workflowRunId}** at **${timestamp}**.

[View blog post](${getBlogUrl(slug)})
`;

    // Get repo info
    const repoData = await github.graphql(`
        query($owner:String!, $repo:String!) {
            repository(owner:$owner, name:$repo) {
                id
                discussionCategories(first:20) {
                    nodes {
                        id
                        name
                    }
                }
            }
        }
    `, { owner, repo });

    const repoId = repoData.repository.id;

    const category = repoData.repository.discussionCategories.nodes
        .find(c => c.name === "Announcements");

    if (!category)
        throw new Error("Discussion category not found");
    
    function walk(currentDir) {
        const results = [];

        function recurse(dir) {
            const entries = fs.readdirSync(dir, { withFileTypes: true });

            for (const entry of entries) {
                const fullPath = path.join(dir, entry.name);

                if (entry.isDirectory()) {
                    recurse(fullPath);
                }
                else if (entry.isFile() && entry.name === "index.qmd") {
                    results.push(fullPath);
                }
            }
        }
        
        recurse(currentDir);
        return results;
    }

    const posts_directory = "blog";
    const posts = walk(`docs/${posts_directory}`);

    // Get all discussions once
    const discussionsData = await github.graphql(`
        query($repoId:ID!) {
            node(id:$repoId) {
                ... on Repository {
                    discussions(first:100) {
                        nodes {
                            id
                            title
                            comments(first:100) {
                                nodes {
                                    id
                                    body
                                }
                            }
                        }
                    }
                }
            }
        }
    `, { repoId });

    const discussions = discussionsData.node.discussions.nodes;

    for (const post of posts) {
        
        const dirPath = path.dirname(post);
        const pathname = "/" + dirPath.replace(/^docs[\/\\]/, "") + "/";
        const discussionBody = discussionBodyTemplate(pathname);

        let discussion = discussions.find(d => d.title === pathname);

        if (!discussion) {
        const created = await github.graphql(`
            mutation($repoId:ID!, $categoryId:ID!, $title:String!, $body:String!) {
                createDiscussion(input:{
                    repositoryId:$repoId
                    categoryId:$categoryId
                    title:$title
                    body:$body
                }) {
                    discussion { id }
                }
            }
        `, {
            repoId,
            categoryId: category.id,
            title: pathname,
            body: discussionBody
        });

        discussion = { id: created.createDiscussion.discussion.id, comments: { nodes: [] } };
            core.info("Discussion created");
        }


        // 2. Find disclaimer comment
        let disclaimerComment =
        discussion.comments?.nodes?.find(c =>
            c.body.includes(MARKER)
        );

        // 3. Create disclaimer comment if missing
        if (!disclaimerComment) {

        const added = await github.graphql(`
            mutation($discussionId:ID!, $body:String!) {
                addDiscussionComment(input:{
                    discussionId:$discussionId
                    body:$body
                }) { comment { id } }
            }
        `, {
            discussionId: discussion.id,
            body: DISCLAIMER
        });

        const commentId = added.addDiscussionComment.comment.id;

        core.info("Disclaimer comment created");
        }

        // 4. Update disclaimer if exists
        else {
            await github.graphql(`
                mutation($commentId:ID!, $body:String!) {
                    updateDiscussionComment(input:{
                        commentId:$commentId
                        body:$body
                    }) { comment { id } }
                }
            `, {
                commentId: disclaimerComment.id,
                body: DISCLAIMER
            });

            core.info("Disclaimer updated");
        }
    }
}

module.exports = run;
